name: Unusuals
version: 0.4.0
main: net.caseif.unusuals.Main
description: Unusual hats, in Minecraft!
author: Maxim Roncacé
website: http://dev.bukkit.org/projects/unusuals

commands:
  unusual:
    description: The main command for the plugin.
    usage: /unusual [args]
    aliases: unusuals
    
permissions:
  unusual.spawn:
    description: Allows spawning of unusuals.
    default: op
  unusual.reload:
    description: Allows reloading of the plugin.
    default: op